remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Welcome to my personal page!]
description: [This personal page is built by Github Pages and Minimal theme.]
